### ISSUE TITLE
Attempt to read property "value" on null

### ISSUE THREAD

**Issue by mrjumpingjack** [sshambar/ExternalAuth#6]
In the OpenID Connect settings php warnings are displayed.

`<br /><b>Warning</b>:  Undefined array key 
/www/htdocs/[domain]/_data/templates_c/p6jhns^7250c247f4231f31f2b0821301f002b673f330a3_0.file.config.tpl.php on line 84

[domain]/_data/templates_c/p6jhns^7250c247f4231f31f2b0821301f002b673f330a3_0.file.config.tpl.php on line 91

Warning: Attempt to read property "value" on null in [domain]/_data/templates_c/p6jhns^7250c247f4231f31f2b0821301f002b673f330a3_0.file.config.tpl.php on line 91
">
`
![Unbenannt](https://github.com/sshambar/ExternalAuth/assets/5872129/686ef215-1c6d-4bd2-92e0-d76f7b1b709a)

**Comment by sshambar** [comment]
I tried and got the same error... but with only OpenIDConnect installed (ExternalAuth not installed)

I think you might need to report the issue with OpenIDConnect: https://github.com/jasperweyne/PiwigoOpenIdConnect/issues
